### ISSUE TITLE
Consistent Wording / Language

### ISSUE THREAD

**Issue by sid351** [NottingHack/rules#10]
Some rules say "We" (such as "We ask that you respect the Hackspace") but it's not immediately clear who "We" is.

Maybe these items should be reworded to avoid the use of "We" and prefer the use of the Hackspace being the object of the sentences?  (It's been a long time since I did any formal English studying so apologies if that's not the correct terminology!)

This may need to extend to the difference between the Hackspace (as a legal entity and a collection of the physical space and it's memberships) and the space (the physical area the Hackspace occupies) as well.

Then again, maybe I'm being a bit too pedantic and these changes would make the wording seem too formal and authoritarian.

**Comment by rlp10** [comment]
Sid, I agree with you in principle. I don't think that it makes a big difference which linguistic perspective we take, but it ought to be clear and consistent throughout. Can you give any examples where you think that it is unclear?

**Comment by geeksareforlife** [comment]
We will review all rules based on thi
