### ISSUE TITLE
Membership of the hackspace and young hackers

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/rules#12]
we should include something about young hackers and under 16's in here

**Comment by rlp10** [comment]
What's the current policy? Is it that under 16s are welcome, if accompanied by a responsible adult?

**Comment by geeksareforlife** [comment]
Yes

**Comment by rlp10** [comment]
I just noticed that the rules already say at https://github.com/NottingHack/rules/blob/rtd-draft/guests-and-visitors.rst:

> Included in this are both children and animals - it is common courtesy to ask on the Google Group 
> before attending the Hackspace with either an animal or a child. The exception to this notification is on 
> open days and nights - members should assume that animals or children may be present at those times.

> Please do not leave your animal, child or guest unattended in the Hackspace. They are your 
> responsibility and must be attended at all times.

dpslwk, does that cover what you wanted?

**Comment by geeksareforlife** [comment]
Young Hackers still needs including - 16-18 year olds can be members of the hackspace only with their parent/guardian's consent

We have a procedure in place, but we should codify this into the rules.

**Comment by geeksareforlife** [comment]
We have some notes, and I will try and work this up into a procedure document, but basically:

Young Hacker (YH) and Parent(s)/Guardians(s) (P) get a tour, from a Trustee
Trustee emphasises the adult nature of the space:

- There is alcohol in the space.  This is not locked away
- There are solvents in the space. These are not locked away
- There are sharp and dangerous tools in the space.  These are not locked away
- Members at the space are not CRB checked - their child may be alone with members
- We will not control their child’s access to the space - their access card will work 24/7

Trustee evaluates YH's maturity level, specifically taking them out of their comfort zone to get a rounded picture

Trustee and P sign off on the YH hacker joining
