### ISSUE TITLE
Termination of membership on non-payment of standing order

### ISSUE THREAD

**Issue by jamesfowkes** [NottingHack/rules#13]
The rule currently states:

"When a member stops paying their standing order, they will become an Ex-Member."

Some clarification of what this means, and the timescales involved would be good. E.g.

How long it is before it is decided a member has not paid their standing order?
Is a member given a chance to correct this before their membership is terminated (i.e. before RFID access is cancelled?)

Maybe a link to a full description of the "termination process" is needed.

**Comment by rlp10** [comment]
I agree. Trustees, are there already policies on these matters that James raises? If not, we can make proposals here. It could be dealt with in only a sentence or two I think.

**Comment by geeksareforlife** [comment]
Yes, but would prefer @dpslwk to elaborate.  His Internet is a bit dodgy where he is for Christmas, so that will be in the new year I expect

**Comment by dpslwk** [comment]
Currently I do a manual members audit around the start of each month.
Any one who has not paid during the last two full months is marked as an ex member

But I'm working on automating this in HMS and having audits ran at least once a week (Wednesday @4am) and depending on the PHP Date math this might mean people are ex members after 60days or 2 months from there last payment, 
the HMS automation will also be adding a warning email to members if we have not seen a payment in the last 1 month and 14 days, at least thats the plan
