### ISSUE TITLE
Rule 0 Numbering

### ISSUE THREAD

**Issue by drazziweht** [NottingHack/rules#17]
We should amend the rule numbering to place rule 0 in section zero or remove the rule 0 designation on the "do not be on fire" rule.

It is disharmonious to have a rule 0 in section 1, we should strive for consistency, harmony any beauty in all that we attempt.

**Comment by rlp10** [comment]
I was also disappointed to note that the numbering of rules do not align with the list on the left here: http://rules.nottinghack.org.uk/en/latest/

**Comment by dpslwk** [comment]
The numbering in the TOC is not something we can control unfortunately

'RepRap' Matt

**Comment by geeksareforlife** [comment]
There might be a configuration option, or different way to generate the
rules. We'd like to keep it at zero, just for the fun of it all

**Comment by rlp10** [comment]
James: When you say "we", do you mean that the trustees have made a decision on this point? Or perhaps it's the royal "we"? ;)

Who is the best person to investigate whether or not there is some configuration change that could be done? If it's Matt, then it looks like we already have an answer, which is that changes to the Table of Contents are not possible.

Another suggestion would be to put "Rule 0" last in the TOC, like this:

1. Rule One: Blah blah
2. Rule Two: Blah blah
3. ...
9. Rule Zero: Blah blah

At least then most of the numbering would be right.

**Comment by geeksareforlife** [comment]
I have made a pull request to fix the Table of Contents.

It means the ToC no longer numbers automatically, nor pulls the titles from the referenced document, but in a document this size that will change very little once agreed, that shouldn't be too much of a problem

**Comment by rlp10** [comment]
Has this been committed? Can we close this issue?

**Comment by geeksareforlife** [comment]
No, we have a policy of not committing our own pull requests, so @dpslwk will do it when he comes back online properly

**Comment by geeksareforlife** [comment]
And this issue will close automatically when it is
