### ISSUE TITLE
membership of the hackspace

### ISSUE THREAD

**Issue by drazziweht** [NottingHack/rules#18]
The membership of the hackspace rule contains amongst other provisions 
"Nottingham Hackspace Ltd is required under Companies Act [1] to keep a record of all members legal name and current address."

I think this section may be confusing the term "Member" as used by the hackspace and "Member" as used by the companies act.

In the companies act a "Member of the company" is a shareholder of the company.
As far as I am aware "Members of the hackspace" are not shareholders of the limited company and hence not in the legal sense members of the company ?.

As a matter of interest who are the shareholders of the limited company ?

**Comment by geeksareforlife** [comment]
There are no shareholders as the company is limited by guarantee, not by
shares.

All members of the hackspace are members of the company. The trustees are
directors.

Technically, you are liable for a pound if the hackspace goes under, but in
practical terms we count this in your membership payment. As part of our
banking reform, we will start keeping that money seperate

**Comment by rlp10** [comment]
James, your conclusion is therefore that the Space is under a legal obligation to keep full names and addresses?

**Comment by geeksareforlife** [comment]
Yes

Happy to be corrected if I'm wrong, but that is how we currently operate

**Comment by drazziweht** [comment]
Ahh, should have realised it would be ltd by guarantee rather than by shares,
Yes, in this case I think you are correct, there does need to be a members register and it looks like the requirements are the same as shareholders of a company ltd by shares, i.e. do need name + address, although there is less requirement to disclose the list.

Given this I will close the issue.

Chris
