### ISSUE TITLE
Grievance Procedure

### ISSUE THREAD

**Issue by rlp10** [NottingHack/rules#20]
I propose that the grievance procedure be brought into the rules, so that it can come into the source control of the github repository and be part of the consultation. It has already become relevant to discussions, including the debate on inclusion of UK law.

Arguably, the greivance procedure already contains its own rules separate from the current rules. For example, it says action will be taken against people who "demonstrate unwillingness to address behaviour which has caused offence, harm or distress to another member or members; or has threatened the safety of the Hackspace". I would suggest amalgamation with the existing rules where possible.

**Comment by drazziweht** [comment]
I was actually thinking about this, Does it make sense to have separate "rules" and a "Grevance procedure"

As far as I can see the grievance procedure is effectively the only mention of any enforcement action available to the trustees (or membership) for breach of the rules, and the wording seems to give significant wriggle room,

It may be worth also considering if we want to look at the Articles and constitution at the same time (since they are the base that underlies all the rules and enforcement of them)

**Comment by geeksareforlife** [comment]
The articles and Constitution can only be changed at an agm

**Comment by rlp10** [comment]
I think amending the articles etc at this stage would be a bridge too far. I only suggest taking on the grievance procedure as well since it appears to overlap with the rules.

**Comment by drazziweht** [comment]
Geeksareforlife said.
"The articles and Constitution can only be changed at an agm"

Certainly the case for the articles.
Where is the restriction on changing the constitution specified ?

**Comment by rlp10** [comment]
I now see however that there is a "SafeSpaces" policy which again appears to overlap with the rules. Do you think that we should bring that into the github repository? Giving it a brief read over, I can see a few things that I would suggest changing there.

**Comment by drazziweht** [comment]
Everything you need to know to not be thrown out of the hackspace should really be in one place, having a Grevance Policy, a safe spaces Policy, a set of rules, a constitution, a religion in the space policy, a sexual harassment policy and a no colouring outside the lines policy makes it very difficult to keep up (ok I may have made one of them up, maybe more than one, are you sure which ones ?)

**Comment by geeksareforlife** [comment]
The restriction for the Constitution is in the Constitution.

I have no objections to bringing the additional policies and procedures
into this GitHub

**Comment by rlp10** [comment]
I agree, Chris. As I think I said elsewhere, it would be helpful if the "rules" tell a member everything that they ought to know about their responsibilities and duties in the Space.

However, I still disagree with you regarding the inclusion of the constitution. That sets out the method by which trustees are elected and then become directors of the limited company, when elections have to be called, how they are run and so forth. I don't see that they come under the same category of "rules", at least, they are not rules for the members (although they are, kind of, rules for the trustees themselves).

**Comment by rlp10** [comment]
Unless there is any other objections, I will attempt my first git-fu and try to create a pull request to bring the greivance procedure and SafeSpaces policy into the rules. Watch this space!

**Comment by drazziweht** [comment]
Was not suggesting the articles + consitution should be part of the rules directly, but maybe an introduction section in the rules which was something like.

The Nottingham Hackspace is governed by a set of documents which include the Articles of association that cover the basic legal status of the hackspace, the constitution which covers how the trustees are elected and the powers of trustees and these rules which cover the day to day activitys of members and how the hackspace operates.


Just tidies it up and links everything into one top level document at least by reference so you can just say "The rules" and it covers everything.

**Comment by rlp10** [comment]
As a proposal, Chris, I'm pretty neutral about it. I would have imagined that information regarding the constitution, rules, legal status etc along with relevant links would go on a relevant page of the website: perhaps the homepage of the wiki for example.

**Comment by geeksareforlife** [comment]
These won't stand alone, they will go in the member's guide, which is also
on GitHub

**Comment by rlp10** [comment]
I propose that we close this issue now that I've created a pull request to include the two policies.

**Comment by geeksareforlife** [comment]
If you add 

closes #20

on the next commit you do to the pull request (I have asked you to update the table of contents with the new files) it will close this issue automatically when I merge it!

**Comment by geeksareforlife** [comment]
I have merged the pull request now
