### ISSUE TITLE
Grievances and Disciplinary Actions

### ISSUE THREAD

**Issue by rlp10** [NottingHack/rules#22]
As I understand it, a *grievance* is when a member makes a complaint to the Hackspace which may or may not be about another member. Normally the grievance procedure would explain who will look into the complaint, how long it might take and what kinds of actions may result from the investigation. It might also say if the person can appeal to an independent person if they are unhappy about the handling or outcome of the grievance. Suitable outcomes to a grievance might be an apology, a mediation meeting, rule changes, new signage or the commencement of a disciplinary investigation, for example.

On the other hand, if the Trustees decide that they should take action against a member (which could arise because of a grievance, or for other reasons - such as just noticing that someone is breaking the rules) then that would be *disciplinary action* and would normally follow a different route, the displinary procedure. This would set out who would investigate, in what timescales and what action could be taken (informal warning, warning, temporary ban, permanent exclusion etc). Again, it may be that there could be an appeal process.

The current grievance procedure seems to conflate these two procedures and I propose that we create a fresh disciplinary procedure and trim back the grievance procedure to specifically cover grievances.

I haven't had much involvement with these types of procedure so the above may not be 100% accurate, but I think it is the way these policies are normally done. If anyone has experience in this area then please do chip in and say if I'm getting things wrong.

**Comment by geeksareforlife** [comment]
To be honest I think the current is much more a disciplinary procedure in the strictest sense.

We called it grievance because that is what London did!  Disciplinary also feels a bit "worky" as well.

**Comment by rlp10** [comment]
Do you agree with the proposal to separate them?

**Comment by geeksareforlife** [comment]
I'm not sure to be honest :)

**Comment by geeksareforlife** [comment]
I have merged them in, so we can now look at what we want changing

**Comment by geeksareforlife** [comment]
Changed to complaints policy via #33, needs additional work but is not part of rules consultation so will happen afterwards
