### ISSUE TITLE
Insurance Policy Obligations

### ISSUE THREAD

**Issue by rlp10** [NottingHack/rules#26]
Further to the discussion in issue #24, do the obligations of the Hackspace to its insurer require any other additions or amendments to the rules? Perhaps someone (me?) can read through and see if there are other duties which should be made clear to the members in the rules.

It would be regrettable if a member were to breach the terms of our insurance because we hadn't properly made clear our obligations to the insurer in the rules.

**Comment by sid351** [comment]
I think it's also useful to mention where an existing rule is based on, if
not there outright because of, a clause in our insurance policy.

**Comment by rlp10** [comment]
That's fine, provided we don't give the impression that its not a rule to take seriously. See my comments in the fourth paragraph here: https://github.com/NottingHack/rules/issues/24#issuecomment-169397553

**Comment by geeksareforlife** [comment]
I'd rather we didn't mention the insurance too much, as per @rlp10 point.

I am happy for people to see the current insurance documents, but they expire at the end of this month and we will get new ones, although probably not too much!

**Comment by geeksareforlife** [comment]
Documents are available here:

https://wiki.nottinghack.org.uk/wiki/Insurance

**Comment by sid351** [comment]
My thinking was that by making it clear that the rule ties directly in to
the insurance of the space it immediately justifies it as a rule.

...Kind of the opposite to seeing it as a rule for the sake of it I
suppose.  It also rationalises the rule pretty quickly.

**Comment by geeksareforlife** [comment]
I don't mind us putting things in purely because of the insurance, or even discussing it here, but if we put that as the reason *inside* the rules then people will ignore it

**Comment by dpslwk** [comment]
Is sooner not reference anything very specific in the insurance docs as they may be changes each year if we shift insurer 

'RepRap' Matt

**Comment by rlp10** [comment]
So perhaps we can close this issue on the basis that we will look at the new insurance documents once they're available?
