### ISSUE TITLE
Rename Filenames

### ISSUE THREAD

**Issue by rlp10** [NottingHack/rules#29]
What do you think about creating a directory called "rules" and moving the rules into it? It might make it more accessible for the non-technical amongst us if all the rules were in the same place and not mixed with other files used for building the documents etc.

Similarly, we could rename the filenames so as to include their number, which would also put them in the right order. For example: "0-do-not-be-on-fire.rst".

**Comment by dpslwk** [comment]
We can not do this because of the folder structure needed for when we include them into the members guide RTD website


‘RepRap’ Matt
