### ISSUE TITLE
Address wording "certify" for inductions in Rule 0

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/rules#3]
Lines in questions

We encourage the safe use of tools and you must self certify that you are comfortable using a tool - except in the case of tools requiring an induction, where the inductor will certify you have been fully inducted.

Inductors do not "certify" a members used for use of a tool but rather ...

**Comment by rlp10** [comment]
How about the following? I can create a pull request if it would be helpful.

> By using a tool you self-certify that you are competent in its use. Additionally, certain tools require
> an induction before you are permitted to use them.

**Comment by geeksareforlife** [comment]
Some work has already been done in PR #5

**Comment by dpslwk** [comment]
closed via #5
