### ISSUE TITLE
Stealing this for another group?

### ISSUE THREAD

**Issue by proffalken** [NottingHack/rules#53]
Hey folks,

I'm in the process of setting up a Hackspace in Monmouth, Wales - are we ok to steal this and amend as we see fit? I'm not too sure what we can and can't do having read the LICENSE file as this isn't my area of expertise...

Thanks,

Matt

**Comment by geeksareforlife** [comment]
You are more than welcome to! I would suggest making sure that they fit
your needs as well though.

J

**Comment by proffalken** [comment]
Magic, thanks :)
